config/routes.rb
Rails.application.routes.draw do
  root 'kanekalons#index', as: 'home'

  resources :kanekalons, only: [:index, :show] do
    get "search", on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kanekalon.rb
# == Schema Information
#
# Table name: kanekalons
#
#  id           :bigint           not null, primary key
#  hex          :string
#  color_name   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  default_mix  :string
#  kami         :string
#  jumbo_braids :string
#  aida         :string
#
class Kanekalon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kanekalons_controller.rb
class KanekalonsController < ApplicationController
  def index
    # searching with autocomplete
    @kanekalons = Kanekalon.order(:color_name).where('color_name ilike ?', "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @kanekalons.map(&:color_name) }
    end
  end

  def show
    @kanekalon = Kanekalon.find(params[:id])
    @single_page_result = case params[:manufacture]
                          when 'Kami'
                            @kanekalon.kami
                          when 'Jumbo'
                            @kanekalon.jumbo_braids
                          when 'Aida'
                            @kanekalon.aida
                          else
                            @kanekalon.default_mix
                          end
  end

  def search
    @kanekalons = Kanekalon.where('color_name ILIKE ? OR hex ILIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    render 'kanekalons/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kanekalons_helper.rb
module KanekalonsHelper
end

app/views/kanekalons/index.html.erb
<h2 class="text-center pb-4">Доступная палитра цветов:</h2>
<% @kanekalons.each do |kanekalon| %>
  <%= link_to kanekalon_path(kanekalon), class: "text-decoration-none text-reset" do %>
    <div class="d-inline-flex justify-content-center align-items-center color-hover" style="width: 220px; height: 80px; background-color: <%= kanekalon.hex %>"><span class="bg-white p-1 invisible"><%= kanekalon.color_name %></span></div>
  <% end %>
<% end %>

app/views/kanekalons/mixing.html.erb
<%= form_with url: kanekalons_mixing_path, method: :get do |form| %>
  <%= form.radio_button :manufacture, "Kami" %>
  <%= form.label :manufacture, "Kami" %>
  <%= form.radio_button :manufacture, "Jumbo" %>
  <%= form.label :manufacture, "Jumbo" %>
  <%= form.select :color_name, @kanekalons.map { |c| [c.color_name, c.color_name, { 'style' => "background-color:" + c.hex + ";"}]}, {}, { :class => 'form-select form-select-lg' }%>
  <%= form.submit %>
<% end %>
<p>Chosen color: <%= @result_color.hex  if @result_color.present?%></p>
<%= @result %>

app/views/kanekalons/show.html.erb
<h2 class="text-center pb-4"><%= @kanekalon.color_name %></h2>
<div class="row">
  <div class="col-6 text-center">
    <h3>Выбери производителя</h3>
    <%= form_with url: kanekalon_path, method: :get do |form| %>
      <%= form.radio_button :manufacture, "Kami" %>
      <%= form.label :manufacture, "Kami" %>
      <%= form.radio_button :manufacture, "Jumbo" %>
      <%= form.label :manufacture, "Jumbo" %>
      <%= form.radio_button :manufacture, "Aida" %>
      <%= form.label :manufacture, "Aida" %>
      <%= form.submit "Mix", class: "btn btn-success d-block w-100" %>
    <% end %>
  </div>
  <div class="col-6" style="width: 50%; background-color: <%= @kanekalon.hex %>"></div>
</div>

<div class="text-center pt-5">
  <h3>Инструкция по смешке:</h3>
  <p><%= @single_page_result %></p>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to "Kanekalon Mix Helper", home_path, class: "navbar-brand col-md-3 col-lg-2 mr-4 px-3 fs-3 text-center", id: "colored" %>

  <%= form_with url: search_kanekalons_path, method: :get, local: true, class: "form-floating d-flex w-100" do |form| %>
    <%= form.text_field :query, id: :query, data: { autocomplete_source: kanekalons_path }, class: "form-control query", placeholder: "Search" %>
    <%= form.label :query, "Search" %>
  <% end %>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">link</a>
    </li>
  </ul>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/layouts/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="sidebar-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
            <polyline points="9 22 9 12 15 12 15 22"></polyline>
          </svg>
          Dashboard <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file">
            <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path>
            <polyline points="13 2 13 9 20 9"></polyline>
          </svg>
          Orders
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart">
            <circle cx="9" cy="21" r="1"></circle>
            <circle cx="20" cy="21" r="1"></circle>
            <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
          </svg>
          Products
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users">
            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
            <circle cx="9" cy="7" r="4"></circle>
            <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
            <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
          </svg>
          Customers
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2">
            <line x1="18" y1="20" x2="18" y2="10"></line>
            <line x1="12" y1="20" x2="12" y2="4"></line>
            <line x1="6" y1="20" x2="6" y2="14"></line>
          </svg>
          Reports
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers">
            <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
            <polyline points="2 17 12 22 22 17"></polyline>
            <polyline points="2 12 12 17 22 12"></polyline>
          </svg>
          Integrations
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Saved reports</span>
      <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle">
          <circle cx="12" cy="12" r="10"></circle>
          <line x1="12" y1="8" x2="12" y2="16"></line>
          <line x1="8" y1="12" x2="16" y2="12"></line>
        </svg>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <polyline points="14 2 14 8 20 8"></polyline>
            <line x1="16" y1="13" x2="8" y2="13"></line>
            <line x1="16" y1="17" x2="8" y2="17"></line>
            <polyline points="10 9 9 9 8 9"></polyline>
          </svg>
          Current month
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <polyline points="14 2 14 8 20 8"></polyline>
            <line x1="16" y1="13" x2="8" y2="13"></line>
            <line x1="16" y1="17" x2="8" y2="17"></line>
            <polyline points="10 9 9 9 8 9"></polyline>
          </svg>
          Last quarter
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <polyline points="14 2 14 8 20 8"></polyline>
            <line x1="16" y1="13" x2="8" y2="13"></line>
            <line x1="16" y1="17" x2="8" y2="17"></line>
            <polyline points="10 9 9 9 8 9"></polyline>
          </svg>
          Social engagement
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <polyline points="14 2 14 8 20 8"></polyline>
            <line x1="16" y1="13" x2="8" y2="13"></line>
            <line x1="16" y1="17" x2="8" y2="17"></line>
            <polyline points="10 9 9 9 8 9"></polyline>
          </svg>
          Year-end sale
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ColorMixing</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/nav' %>
<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/sidebar' %>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="container mt-5">
        <%= yield %>
      </div>
    </main>
  </div>
</div>
</body>
</html>